# Generated by Django 3.0 on 2022-01-20 19:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0003_auto_20220120_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktail',
            name='color',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=6), blank=True, default=list, size=None),
        ),
    ]
