# Generated by Django 3.0 on 2022-01-21 08:09

from django.db import migrations
from django.contrib.auth.models import User


def create_admin_user(apps, schema_editor):
    User.objects.create_superuser('admin', email='admin@admin.com', password='admin')


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0004_auto_20220120_1939'),
    ]

    operations = [
        migrations.RunPython(create_admin_user)
    ]
